name: Database CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  mysql-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD || 'Secret5555' }}
          MYSQL_DATABASE: project_db
        ports:
          - 3306:3306
        options: >-
          --name automated-mysql-server
          --health-cmd="mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=15
          --health-start-period=20s
          --entrypoint sh
        # enable general log for logs visibility
        # Use entrypoint to pass mysqld args
        # run mysqld as command with logs:
        # (Workaround: override entrypoint to sh -c 'exec mysqld ...')
        # But GitHub "services" doesn't support command easily; okay to skip general log in CI.

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mysql client & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write mysql.cnf from GitHub Secret
        run: |
          mkdir -p .secrets
          cat > .secrets/mysql.cnf <<'EOF'
          [client]
          host=127.0.0.1
          user=root
          password=${{ secrets.MYSQL_ROOT_PASSWORD || 'Secret5555' }}
          port=3306
          database=project_db
          EOF

      - name: Wait for DB
        run: |
          for i in $(seq 1 60); do
            mysql --defaults-extra-file=.secrets/mysql.cnf -e "SELECT 1;" && break
            sleep 2
          done

      - name: Initial Schema Deployment
        run: |
          mysql --defaults-extra-file=.secrets/mysql.cnf < sql/01_create_schema.sql

      - name: Schema Update (add humidity)
        run: |
          mysql --defaults-extra-file=.secrets/mysql.cnf < sql/02_add_humidity.sql

      - name: Data Seeding
        run: |
          mysql --defaults-extra-file=.secrets/mysql.cnf < sql/03_seed_data.sql

      - name: Concurrent Query Execution (Python)
        run: |
          python scripts/multi_thread_queries.py --config .secrets/mysql.cnf | tee pipeline_run.log

      - name: Validation
        run: |
          echo "== Table structure =="
          mysql --defaults-extra-file=.secrets/mysql.cnf -e "SHOW CREATE TABLE project_db.ClimateData\G"
          echo "== Columns check =="
          mysql --defaults-extra-file=.secrets/mysql.cnf -e "SHOW COLUMNS FROM project_db.ClimateData LIKE 'humidity';"
          echo "== Counts =="
          mysql --defaults-extra-file=.secrets/mysql.cnf -e "SELECT COUNT(*) AS total_rows FROM project_db.ClimateData;"
          echo "== Sample hot rows =="
          mysql --defaults-extra-file=.secrets/mysql.cnf -e "SELECT location, record_date, temperature, humidity FROM project_db.ClimateData WHERE temperature > 20 ORDER BY record_date DESC LIMIT 10;"

      - name: Upload pipeline logs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: |
            pipeline_run.log
